apiVersion: apps/v1
kind: Deployment
metadata:
      name: devops-ci-demo
      labels:
            app: devops-ci-demo
spec:
    selector:
        matchLabels:
            app: devops-ci-demo
    replicas: 1
    template:
        metadata:
            name: devops-ci-demo
            labels:
                app: devops-ci-demo
        spec:
            containers:
                -   name: devops-ci-demo
                    image: local/devops-ci-demo-img:latest
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
    name: devops-ci-demo
    labels:
        app: devops-ci-demo
spec:
    type: NodePort
    selector:
        app: devops-ci-demo
    ports:
        -   name: http
            port: 8080
            targetPort: 8088