apiVersion: apps/v1
kind: Deployment
metadata:
    name: devops-demo
    labels:
        app: devops-demo
spec:
    selector:
        matchLabels:
            app: devops-demo
    replicas: 2
    template:
        metadata:
            name: devops-demo
            labels:
                app: devops-demo
        spec:
            containers:
                - name: devops-demo
                  image: local/devops-demo:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
    name: devops-demo
    labels:
        app: devops-demo
spec:
    type: NodePort
    selector:
        app: devops-demo
    ports:
        - name: http
          port: 8080
          targetPort: 8088