name:  CD -Deploy to Minikube using Github Actions
on:
    push:
        branches:
          [ main ] #main branch
    pull_request:
        branches:
          [ main ] #main branch
jobs:
    job1:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                name: Start Minikube
            -   id: minikube
                uses: medyagh/setup-minikube@latest
            -   name: try the cluster
                run: |
                    kubectl get pods -A
            -   name: Build Image
                run: |
                    export SHELL=/bin/bash
                    eval $(minikube -p minikube docker-env)
                    docker build -f ./Dockerfile -t local/devops-demo .
                    echo -n "Verifying images : "
                    docker images
            -   name: Deploy to Minikube
                run: |
                    kubectl apply -f deployment.yaml
                    kubectl wait --for=condition=Ready pod -l app=devops-demo
                    kubectl get all
            -   name: Test service URLs
                run: |
                    echo "SERVICE URL: $(minikube service devops-demo --url)"
                    kubectl port-forward service/devops-demo 8080:8080 &> /dev/null &
                    sleep 5
                    kubectl port-forward service/devops-demo 8080:8080 &> /dev/null &
            -   run: |
                    curl -i http://localhost:8080
            -   name: Cleanup
                run: |
                    eval $(minikube docker-env -u)
                    minikube delete